### ISSUE TITLE
MemoryError：patch_dat = np.zeros(shape=(len(candidates), 28, 42, 42), dtype=np.float32)

### ISSUE THREAD

**Issue by FancccyRay** [ku-milab/MGICNN#7]
Hi! I was trying to rerun the code and reproduce the result, After running the code 
I got such error:
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    train_proposed()
  File "main.py", line 12, in train_proposed
    trn_dat, trn_lbl, tst_dat, tst_lbl = utils.load_fold()
  File "/home/fancywu/Desktop/Lung_nodule_detection/Test_code_data/download_code/MGICNN-master/utils.py", line 188, in load_fold
    split_fold()
  File "/home/fancywu/Desktop/Lung_nodule_detection/Test_code_data/download_code/MGICNN-master/utils.py", line 112, in split_fold
    augment_data()
  File "/home/fancywu/Desktop/Lung_nodule_detection/Test_code_data/download_code/MGICNN-master/utils.py", line 89, in augment_data
    load_raw_data()
  File "/home/fancywu/Desktop/Lung_nodule_detection/Test_code_data/download_code/MGICNN-master/utils.py", line 60, in load_raw_data
    patch_dat = np.zeros(shape=(len(candidates), 28, 42, 42), dtype=np.float32)
MemoryError
___________________________________________________________________________-
I computed the size of patch_dat, and found it costs too much memory,  138.91505151987076GiB, 
I wonder is there any ways to reduce the memory cost??  How can I deal with this problem?

**Comment by liuzwin98** [comment]
I got the same problem. I don't know what these constant parameters(28, 42, 42) mean. Did you solve the problem?

**Comment by torki-hossein** [comment]
Hi, you must disable memory over commitment in your OS, for ex: in ubuntu run below command:
echo 1 > /proc/sys/vm/overcommit_memory

another solution that you can use is splitting folds to some parts.
